services:
    mate_rest.manager:
        class: Mate\RestBundle\Service\Manager
        arguments: ['@doctrine']
        calls:
            - [setPropertyAccessor, ['@property_accessor']]
            - [setSerializer, ['@jms_serializer.serializer']]

    mate_rest.system:
        class: Mate\RestBundle\Service\RestSystem
        parent: mate_rest.manager
        calls:
            - [setValidator, ['@validator']]
            - [setAnnotationObserver, ['@mate_rest.annotation.observer']]

    mate_rest.annotation.observer:
        class: Mate\RestBundle\Annotation\AnnotationObserver

    mate_rest.request:
        class: Mate\RestBundle\Service\Request
        arguments: ["@request_stack"]

    mate_rest.listener.json_exception:
        class: Mate\RestBundle\Listener\JsonExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -10 }